//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam_qusetion
    {
        public int ID { get; set; }
        public int Exam_Id { get; set; }
        public int Question_Id { get; set; }
        public double Grade { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual question question { get; set; }
    }
}
