//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class msqmultivalue
    {
        public int MCQCode { get; set; }
        public string ModelAnswer { get; set; }
        public bool correct { get; set; }
    
        public virtual multichoice multichoice { get; set; }
    }
}
