//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_exam_student
    {
        public int StuId { get; set; }
        public int ExamCode { get; set; }
        public int ID { get; set; }
        public bool Taken { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual student student { get; set; }
    }
}
