//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_student_qusetion_exam
    {
        public int StudentId { get; set; }
        public int QustCode { get; set; }
        public int ExamCode { get; set; }
        public string Answer { get; set; }
        public string ModelAnswer { get; set; }
        public double DegreeMark { get; set; }
        public int ID { get; set; }
    }
}
