//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_course_student
    {
        public int ID { get; set; }
        public Nullable<int> StuId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual course course { get; set; }
        public virtual student student { get; set; }
    }
}
