//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.rel_course_student = new HashSet<rel_course_student>();
            this.rel_exam_student = new HashSet<rel_exam_student>();
        }
    
        public string StuEmail { get; set; }
        public int StuId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MatrailStatus { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int ITBid { get; set; }
    
        public virtual rel_branch_track_intake rel_branch_track_intake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_course_student> rel_course_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_exam_student> rel_exam_student { get; set; }
        public virtual user user { get; set; }
    }
}
