//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class textquestion
    {
        public int QustCode { get; set; }
        public string ModelAnswer { get; set; }
        public int TxtCode { get; set; }
        public string question { get; set; }
    
        public virtual question question1 { get; set; }
    }
}
